name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.ARTIFACTORY_URL }}
    - name: Build
      run: docker build -t demo_ui .
    - name: Push
      run: |
           docker tag demo:latest ${{ secrets.ARTIFACTORY_URL }}/harness-demo-ui/demo-ui
           docker push ${{ secrets.ARTIFACTORY_URL }}/harness-demo-ui/demo-ui

#  deploy:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: HTTP Request Action
#        uses: fjogeleit/http-request-action@v1.8.0
#        with:
#          url: 'https://app.harness.io/gateway/api/webhooks/CcTEeEYScYNb0XwduQvmTi2vPPmEOfwbYt51zaE1?accountId=JUGxua0aTTSJ6X3K7Y21Ug'
#          method: 'POST'
#          contentType: 'application/json'
#          data: '{"application":"BE1tH06USyupdp-eaTk6xQ","parameters":{"Environment":"Dev","Service":"backend","InfraDefinition_KUBERNETES":"Dev-k8s","jiraRequest":"HAR-3"},"artifacts":[{"artifactSourceName":"demo-local-docker-repo_demo-backend-app (demo-local-docker-repo/demo-backend-app)","service":"backend","buildNumber":"latest"}]}'
      

